/**
 * Proves the TypeScript propagation mirror agrees with the Python original.
 * shared/fixtures/propagation_cases.json is generated by
 * scripts/generate_propagation_fixtures.py from simulation/core/propagation.py
 * and the four demo models; if this test fails, one side changed without
 * the other.
 */
import { describe, expect, it } from "vitest";
import cases from "@shared/fixtures/propagation_cases.json";
import { computeHazard, type HazardKind } from "./hazards";
import { frontState, paramsFromConfig } from "./kinematics";
import { distanceToCoastAlongHeading, nearestShoreDistance, shoreX, type ShoreParams } from "./world";

const TOL = 1e-6;

interface FixtureShore {
  base_x_km: number;
  terms: { amp: number; freq: number; phase: number }[];
  land_sign: number;
}

const shoreOf = (c: { shore: FixtureShore }): ShoreParams => ({
  baseXKm: c.shore.base_x_km,
  terms: c.shore.terms,
  landSign: c.shore.land_sign,
});

describe("demo world mirror", () => {
  it("shore_x matches", () => {
    for (const c of cases.shore_x) expect(shoreX(c.y, shoreOf(c))).toBeCloseTo(c.x, 6);
  });

  it("distance_to_coast matches", () => {
    for (const c of cases.distance_to_coast) {
      const d = distanceToCoastAlongHeading(c.x, c.y, c.heading, shoreOf(c));
      if (c.distance === null) expect(d).toBeNull();
      else expect(d).toBeCloseTo(c.distance, 4);
    }
  });

  it("nearest_shore matches", () => {
    for (const c of cases.nearest_shore) expect(nearestShoreDistance(c.x, c.y, shoreOf(c))).toBeCloseTo(c.distance, 4);
  });

  it("front_state matches", () => {
    for (const c of cases.front_state) {
      const params = paramsFromConfig(c.params, { speedKmh: 1, spreadRadiusKm: 1 });
      const fs = frontState(params, c.elapsed_minutes, c.stop_at_coast, shoreOf(c));
      const r = c.result;
      expect(fs.traveledKm).toBeCloseTo(r.traveled_km, 4);
      expect(Math.abs(fs.positionXKm - r.position_x_km)).toBeLessThan(TOL);
      expect(Math.abs(fs.positionYKm - r.position_y_km)).toBeLessThan(TOL);
      expect(fs.coastDistanceTotalKm).toEqual(r.coast_distance_total_km);
      if (r.distance_to_coast_km === null) expect(fs.distanceToCoastKm).toBeNull();
      else expect(fs.distanceToCoastKm!).toBeCloseTo(r.distance_to_coast_km, 6);
      expect(fs.arrivalProgress).toBeCloseTo(r.arrival_progress, 6);
      expect(fs.arrived).toBe(r.arrived);
      if (r.eta_minutes === null) expect(fs.etaMinutes).toBeNull();
      else expect(fs.etaMinutes!).toBeCloseTo(r.eta_minutes, 6);
      expect(fs.minutesSinceArrival).toBeCloseTo(r.minutes_since_arrival, 6);
    }
  });

  it("model hazard formulas match", () => {
    const kindOf: Record<string, HazardKind> = {
      tsunami: "tsunami",
      cyclone: "cyclone",
      oil_spill: "oil_spill",
      coastal_flood: "coastal_flood",
    };
    for (const m of cases.models) {
      const kind = kindOf[m.disaster_type];
      const params = paramsFromConfig(m.params, {
        speedKmh: m.params.speed_kmh,
        spreadRadiusKm: m.params.spread_radius_km,
      });
      for (const f of m.frames) {
        const snap = computeHazard(kind, params, f.elapsed_minutes, shoreOf(m));
        const h = f.hazard_state as Record<string, number | boolean | string | null | { x: number; y: number }>;
        expect(snap.phase).toBe(h.phase);
        expect(snap.radiusKm).toBeCloseTo(h.radius_km as number, 3);
        expect(snap.front.positionXKm).toBeCloseTo((h.position_km as { x: number }).x, 3);
        if (kind === "tsunami") {
          expect(snap.waveHeightM!).toBeCloseTo(h.wave_height_m as number, 3);
          expect(snap.coastalImpactM!).toBeCloseTo(h.coastal_impact_m as number, 3);
        }
        if (kind === "cyclone") expect(snap.windSpeedKt!).toBeCloseTo(h.wind_speed_kt as number, 2);
        if (kind === "oil_spill") {
          expect(snap.slickRadiusKm!).toBeCloseTo(h.slick_radius_km as number, 3);
          expect(snap.concentrationIndex!).toBeCloseTo(h.concentration_index as number, 4);
        }
        if (kind === "coastal_flood") expect(snap.waterLevelM!).toBeCloseTo(h.water_level_m as number, 3);
      }
    }
  });
});

describe("recorded-frame replay", () => {
  it("rebuilds the same snapshot from a recorded hazard_state as the live formulas produce", async () => {
    const { snapshotFromRecordedFrame } = await import("./hazards");
    const kindOf: Record<string, HazardKind> = { tsunami: "tsunami", cyclone: "cyclone", oil_spill: "oil_spill", coastal_flood: "coastal_flood" };
    for (const m of cases.models) {
      const kind = kindOf[m.disaster_type];
      const params = paramsFromConfig(m.params, { speedKmh: m.params.speed_kmh, spreadRadiusKm: m.params.spread_radius_km });
      for (const f of m.frames) {
        const live = computeHazard(kind, params, f.elapsed_minutes, shoreOf(m));
        const replay = snapshotFromRecordedFrame(kind, f.hazard_state as never, f.elapsed_minutes);
        expect(replay.phase).toBe(live.phase);
        expect(replay.radiusKm).toBeCloseTo(live.radiusKm, 3);
        expect(replay.front.positionXKm).toBeCloseTo(live.front.positionXKm, 3);
        expect(replay.front.positionYKm).toBeCloseTo(live.front.positionYKm, 3);
        expect(replay.front.arrived).toBe(live.front.arrived);
        expect(replay.intensity01).toBeCloseTo(live.intensity01, 3);
        // Labels can differ in the last digit (backend rounds to 3 dp before
        // toFixed(1)); the underlying numbers must agree.
        if (kind === "tsunami") expect(replay.waveHeightM!).toBeCloseTo(live.waveHeightM!, 3);
        if (kind === "coastal_flood") expect(replay.waterLevelM!).toBeCloseTo(live.waterLevelM!, 3);
      }
    }
  });
});

describe("structure exposure mirror", () => {
  it("matches the Python assessment for every fixture frame", async () => {
    const { assessStructures, geometryFromSnapshot } = await import("./structures");
    const kindOf: Record<string, HazardKind> = { tsunami: "tsunami", cyclone: "cyclone", oil_spill: "oil_spill", coastal_flood: "coastal_flood" };
    for (const m of cases.models) {
      const kind = kindOf[m.disaster_type];
      const params = paramsFromConfig(m.params, { speedKmh: m.params.speed_kmh, spreadRadiusKm: m.params.spread_radius_km });
      for (const f of m.frames) {
        const snap = computeHazard(kind, params, f.elapsed_minutes, shoreOf(m));
        const impacts = assessStructures(m.structures as never, geometryFromSnapshot(snap), shoreOf(m));
        const expected = f.infrastructure_impacts as { structure_id: string; exposure: number; status: string; distance_km: number }[];
        expect(impacts.map((i) => i.structure_id)).toEqual(expected.map((e) => e.structure_id));
        impacts.forEach((i, idx) => {
          expect(i.exposure).toBeCloseTo(expected[idx].exposure, 3);
          expect(i.distance_km).toBeCloseTo(expected[idx].distance_km, 2);
          expect(i.status).toBe(expected[idx].status);
        });
      }
    }
  });
});
