/**
 * Demo shoreline world — TypeScript MIRROR of simulation/core/propagation.py.
 *
 * SIMPLIFIED DEMONSTRATION geometry: a 300 km square, ocean by default west
 * of an analytic shoreline curve and land east of it; `landSign` (+1 = land
 * east, -1 = land west) selects which. Not a coastline, not
 * bathymetry. The constants come from shared/constants/demo_world.json and
 * the formulas are ported line-for-line; `mirror.test.ts` replays
 * shared/fixtures/propagation_cases.json (generated by the Python side) to
 * prove the two agree to 1e-6 km. If you change one side, change the other
 * and regenerate the fixtures (scripts/generate_propagation_fixtures.py).
 */
import demoWorld from "@shared/constants/demo_world.json";
import type { TownProfile, TownShoreTerm } from "@shared/types";

export const WORLD_KM: number = demoWorld.world_km;
export const WORLD_ID: string = demoWorld.world_id;
const SHORE_BASE_X_KM: number = demoWorld.shore_base_x_km;
const SHORE_TERMS: ReadonlyArray<{ amp: number; freq: number; phase: number }> = demoWorld.shore_terms;
const MARCH_STEP_KM: number = demoWorld.march_step_km;
const MARCH_MAX_KM: number = demoWorld.march_max_km;

export const WORLD_DEFAULTS = demoWorld.defaults;

/** The shoreline's shape and which side of it is land — the fictional demo
 * constants by default, or a curated real city's fitted curve
 * (architecture.md ADR-009). `landSign` is +1 when land lies east of the
 * curve (a west-facing coast) and -1 when it lies west (east-facing); it is
 * the only thing that distinguishes the two. */
export interface ShoreParams {
  baseXKm: number;
  terms: ReadonlyArray<TownShoreTerm>;
  landSign: number;
}

export const DEFAULT_SHORE: ShoreParams = { baseXKm: SHORE_BASE_X_KM, terms: SHORE_TERMS, landSign: 1 };

/** The `ShoreParams` for a curated real city (architecture.md ADR-009).
 * The single place a TownProfile becomes a shoreline, so the orientation
 * cannot be dropped at one call site and kept at another. */
export function shoreParamsForTown(town: TownProfile): ShoreParams {
  return {
    baseXKm: town.shore_base_x_km,
    terms: town.shore_terms,
    landSign: town.ocean_side === "west" ? 1 : -1,
  };
}

/** East-west position of the shoreline at northing `yKm`. */
export function shoreX(yKm: number, shore: ShoreParams = DEFAULT_SHORE): number {
  let x = shore.baseXKm;
  for (const { amp, freq, phase } of shore.terms) {
    x += amp * Math.sin((2 * Math.PI * freq * yKm) / WORLD_KM + phase);
  }
  return x;
}

/** Signed distance inland from the shoreline in km; negative offshore.
 * Carries the coast's orientation. */
export function landDepthKm(xKm: number, yKm: number, shore: ShoreParams = DEFAULT_SHORE): number {
  return shore.landSign * (xKm - shoreX(yKm, shore));
}

export function isLand(xKm: number, yKm: number, shore: ShoreParams = DEFAULT_SHORE): boolean {
  return landDepthKm(xKm, yKm, shore) >= 0;
}

/** Compass heading -> unit (dx, dy): 0° = +y (north), 90° = +x (east). */
export function headingVector(headingDeg: number): [number, number] {
  const rad = (headingDeg * Math.PI) / 180;
  return [Math.sin(rad), Math.cos(rad)];
}

/** Distance from (x, y) to the first land point along `headingDeg`, or null
 * if that line never reaches land within the world; 0 if already on land. */
export function distanceToCoastAlongHeading(xKm: number, yKm: number, headingDeg: number, shore: ShoreParams = DEFAULT_SHORE): number | null {
  if (isLand(xKm, yKm, shore)) return 0;
  const [dx, dy] = headingVector(headingDeg);
  let traveled = 0;
  while (traveled < MARCH_MAX_KM) {
    const nxt = traveled + MARCH_STEP_KM;
    if (isLand(xKm + dx * nxt, yKm + dy * nxt, shore)) {
      let lo = traveled;
      let hi = nxt;
      for (let i = 0; i < 12; i++) {
        const mid = 0.5 * (lo + hi);
        if (isLand(xKm + dx * mid, yKm + dy * mid, shore)) hi = mid;
        else lo = mid;
      }
      return round4(hi);
    }
    traveled = nxt;
  }
  return null;
}

/** Straight-line distance to the closest shoreline sample within ±80 km of
 * northing; 0 on land. Telemetry only. */
export function nearestShoreDistance(xKm: number, yKm: number, shore: ShoreParams = DEFAULT_SHORE): number {
  if (isLand(xKm, yKm, shore)) return 0;
  let best = Number.POSITIVE_INFINITY;
  const y0 = yKm - 80;
  for (let i = 0; i <= 160; i++) {
    const yi = y0 + i;
    const d = Math.hypot(shoreX(yi, shore) - xKm, yi - yKm);
    if (d < best) best = d;
  }
  return round4(best);
}

/** An offshore origin `offsetKm` out to sea from the shoreline at `yKm`,
 * on whichever side the water is. Clamped inside the world square. */
export function offshoreOriginX(yKm: number, offsetKm: number, shore: ShoreParams = DEFAULT_SHORE): number {
  const x = shoreX(yKm, shore) - shore.landSign * offsetKm;
  return Math.max(2, Math.min(WORLD_KM - 2, x));
}

export function clamp(value: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, value));
}

/** Python's round(x, 4) — half-to-even is irrelevant at this precision for
 * the values involved; Math.round on the scaled value matches the fixture
 * output to well under the 1e-6 tolerance. */
export function round4(value: number): number {
  return Math.round(value * 10000) / 10000;
}
