/**
 * Demo shoreline world — TypeScript MIRROR of simulation/core/propagation.py.
 *
 * SIMPLIFIED DEMONSTRATION geometry: a 300 km square, ocean west of an
 * analytic shoreline curve, land east of it. Not a coastline, not
 * bathymetry. The constants come from shared/constants/demo_world.json and
 * the formulas are ported line-for-line; `mirror.test.ts` replays
 * shared/fixtures/propagation_cases.json (generated by the Python side) to
 * prove the two agree to 1e-6 km. If you change one side, change the other
 * and regenerate the fixtures (scripts/generate_propagation_fixtures.py).
 */
import demoWorld from "@shared/constants/demo_world.json";

export const WORLD_KM: number = demoWorld.world_km;
export const WORLD_ID: string = demoWorld.world_id;
const SHORE_BASE_X_KM: number = demoWorld.shore_base_x_km;
const SHORE_TERMS: ReadonlyArray<{ amp: number; freq: number; phase: number }> = demoWorld.shore_terms;
const MARCH_STEP_KM: number = demoWorld.march_step_km;
const MARCH_MAX_KM: number = demoWorld.march_max_km;

export const WORLD_DEFAULTS = demoWorld.defaults;

/** East-west position of the shoreline at northing `yKm`. */
export function shoreX(yKm: number): number {
  let x = SHORE_BASE_X_KM;
  for (const { amp, freq, phase } of SHORE_TERMS) {
    x += amp * Math.sin((2 * Math.PI * freq * yKm) / WORLD_KM + phase);
  }
  return x;
}

export function isLand(xKm: number, yKm: number): boolean {
  return xKm >= shoreX(yKm);
}

/** Compass heading -> unit (dx, dy): 0° = +y (north), 90° = +x (east). */
export function headingVector(headingDeg: number): [number, number] {
  const rad = (headingDeg * Math.PI) / 180;
  return [Math.sin(rad), Math.cos(rad)];
}

/** Distance from (x, y) to the first land point along `headingDeg`, or null
 * if that line never reaches land within the world; 0 if already on land. */
export function distanceToCoastAlongHeading(xKm: number, yKm: number, headingDeg: number): number | null {
  if (isLand(xKm, yKm)) return 0;
  const [dx, dy] = headingVector(headingDeg);
  let traveled = 0;
  while (traveled < MARCH_MAX_KM) {
    const nxt = traveled + MARCH_STEP_KM;
    if (isLand(xKm + dx * nxt, yKm + dy * nxt)) {
      let lo = traveled;
      let hi = nxt;
      for (let i = 0; i < 12; i++) {
        const mid = 0.5 * (lo + hi);
        if (isLand(xKm + dx * mid, yKm + dy * mid)) hi = mid;
        else lo = mid;
      }
      return round4(hi);
    }
    traveled = nxt;
  }
  return null;
}

/** Straight-line distance to the closest shoreline sample within ±80 km of
 * northing; 0 on land. Telemetry only. */
export function nearestShoreDistance(xKm: number, yKm: number): number {
  if (isLand(xKm, yKm)) return 0;
  let best = Number.POSITIVE_INFINITY;
  const y0 = yKm - 80;
  for (let i = 0; i <= 160; i++) {
    const yi = y0 + i;
    const d = Math.hypot(shoreX(yi) - xKm, yi - yKm);
    if (d < best) best = d;
  }
  return round4(best);
}

export function clamp(value: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, value));
}

/** Python's round(x, 4) — half-to-even is irrelevant at this precision for
 * the values involved; Math.round on the scaled value matches the fixture
 * output to well under the 1e-6 tolerance. */
export function round4(value: number): number {
  return Math.round(value * 10000) / 10000;
}
