"""rag_sources / rag_ingestion_log (Prompt 16 — RAG pipeline)

Postgres side of the source registry: `rag_sources` holds one row per
ingested authoritative document (checksum, trust level, disaster
categories); chunks and embeddings live only in ChromaDB
(`rag/vectorstore/`), never here (CLAUDE.md §24). `rag_ingestion_log` is an
append-only audit of every ingestion attempt, including skipped
(checksum-unchanged) and failed runs.

Revision ID: 1bc3c8e45abe
Revises: 9a1f63c05d72
Create Date: 2026-09-12 18:32:13.719198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bc3c8e45abe'
down_revision: Union[str, Sequence[str], None] = '9a1f63c05d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_sources',
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('trust_level', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', name='rag_trust_level'), nullable=False),
    sa.Column('disaster_types', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_test_fixture', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_sources_source_id'), 'rag_sources', ['source_id'], unique=True)
    op.create_table('rag_ingestion_log',
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rag_source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rag_source_id'], ['rag_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_ingestion_log_source_id'), 'rag_ingestion_log', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_ingestion_log_source_id'), table_name='rag_ingestion_log')
    op.drop_table('rag_ingestion_log')
    op.drop_index(op.f('ix_rag_sources_source_id'), table_name='rag_sources')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###
    # Autogenerate never drops the PG ENUM type it created for `trust_level`
    # (database.md's GeoAlchemy2/enum gotcha) — left in place, downgrade
    # would fail on the next upgrade attempting to recreate it otherwise.
    sa.Enum(name='rag_trust_level').drop(op.get_bind(), checkfirst=True)
