"""foundational schema

Revision ID: 34d773b93c0a
Revises: 
Create Date: 2026-09-11 23:00:09.079151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d773b93c0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_assets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.Enum('HOSPITAL', 'POLICE_STATION', 'FIRE_STATION', 'SHELTER', 'PORT', 'AIRPORT', 'BRIDGE', 'ROAD', 'POWER_STATION', 'WATER_TREATMENT_FACILITY', 'EMERGENCY_OPERATIONS_CENTER', name='asset_type'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='asset_criticality'), nullable=False),
    sa.Column('geometry', Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Not created here — GeoAlchemy2's DDL event creates this GIST index when
    # the table above is created (spatial_index=True, the model's default).
    # An explicit op.create_index here would collide with that event.
    op.create_index(op.f('ix_infrastructure_assets_asset_type'), 'infrastructure_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_infrastructure_assets_criticality'), 'infrastructure_assets', ['criticality'], unique=False)
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disaster_type', sa.Enum('FLOOD', 'FLASH_FLOOD', 'COASTAL_FLOOD', 'STORM_SURGE', 'CYCLONE', 'TSUNAMI', 'OIL_SPILL', 'CHEMICAL_POLLUTION', 'SEARCH_RESCUE', name='disaster_type'), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='scenario_status'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # See infrastructure_assets above — GeoAlchemy2's DDL event handles this one too.
    op.create_index(op.f('ix_scenarios_disaster_type'), 'scenarios', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('scenario_versions',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('scenario_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'version_number', name='uq_scenario_version_number')
    )
    op.create_index(op.f('ix_scenario_versions_scenario_id'), 'scenario_versions', ['scenario_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='simulation_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('timestep_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_identifier', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_scenario_version_id'), 'simulation_runs', ['scenario_version_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_status'), 'simulation_runs', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_type', sa.Enum('SCENARIO_CREATED', 'SCENARIO_MODIFIED', 'SIMULATION_STARTED', 'SIMULATION_COMPLETED', 'RISK_RECALCULATED', 'AI_ANALYSIS_EXECUTED', 'RECOMMENDATION_GENERATED', 'RESPONSE_PLAN_GENERATED', name='event_type'), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('simulation_run_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_scenario_id'), 'audit_events', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_audit_events_simulation_run_id'), 'audit_events', ['simulation_run_id'], unique=False)
    op.create_table('incident_action_plans',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('incident_overview', sa.Text(), nullable=True),
    sa.Column('situation_summary', sa.Text(), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operational_period', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evacuation_strategy', sa.Text(), nullable=True),
    sa.Column('safety_considerations', sa.Text(), nullable=True),
    sa.Column('communication_plan', sa.Text(), nullable=True),
    sa.Column('environmental_considerations', sa.Text(), nullable=True),
    sa.Column('monitoring_plan', sa.Text(), nullable=True),
    sa.Column('decision_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_action_plans_simulation_run_id'), 'incident_action_plans', ['simulation_run_id'], unique=False)
    op.create_table('response_recommendations',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='recommendation_priority'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('responsible_role', sa.String(length=200), nullable=True),
    sa.Column('deadline_timestep', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('RULE_BASED', 'SIMULATION_ANALYSIS', 'AI_AGENT', 'HUMAN_OPERATOR', name='recommendation_source'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'IMPLEMENTED', name='recommendation_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_recommendations_priority'), 'response_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_response_recommendations_simulation_run_id'), 'response_recommendations', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_response_recommendations_status'), 'response_recommendations', ['status'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('OVERALL', 'POPULATION', 'INFRASTRUCTURE', 'ENVIRONMENTAL', 'ECONOMIC', 'EVACUATION', 'ACCESSIBILITY', name='risk_category'), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('timestep', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_category'), 'risk_assessments', ['category'], unique=False)
    op.create_index(op.f('ix_risk_assessments_level'), 'risk_assessments', ['level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_simulation_run_id'), 'risk_assessments', ['simulation_run_id'], unique=False)
    op.create_table('simulation_artifacts',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('NETCDF', 'ZARR', 'GEOTIFF', 'JSON', 'OTHER', name='artifact_type'), nullable=False),
    sa.Column('storage_location', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('timestep_start', sa.Integer(), nullable=True),
    sa.Column('timestep_end', sa.Integer(), nullable=True),
    sa.Column('spatial_extent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_artifacts_artifact_type'), 'simulation_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_simulation_artifacts_simulation_run_id'), 'simulation_artifacts', ['simulation_run_id'], unique=False)
    op.create_table('vulnerability_assessments',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('infrastructure_asset_id', sa.UUID(), nullable=True),
    sa.Column('region_label', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='vulnerability_level'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('timestep', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_assessments_infrastructure_asset_id'), 'vulnerability_assessments', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_assessments_level'), 'vulnerability_assessments', ['level'], unique=False)
    op.create_index(op.f('ix_vulnerability_assessments_simulation_run_id'), 'vulnerability_assessments', ['simulation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_assessments_simulation_run_id'), table_name='vulnerability_assessments')
    op.drop_index(op.f('ix_vulnerability_assessments_level'), table_name='vulnerability_assessments')
    op.drop_index(op.f('ix_vulnerability_assessments_infrastructure_asset_id'), table_name='vulnerability_assessments')
    op.drop_table('vulnerability_assessments')
    op.drop_index(op.f('ix_simulation_artifacts_simulation_run_id'), table_name='simulation_artifacts')
    op.drop_index(op.f('ix_simulation_artifacts_artifact_type'), table_name='simulation_artifacts')
    op.drop_table('simulation_artifacts')
    op.drop_index(op.f('ix_risk_assessments_simulation_run_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_category'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_response_recommendations_status'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_simulation_run_id'), table_name='response_recommendations')
    op.drop_index(op.f('ix_response_recommendations_priority'), table_name='response_recommendations')
    op.drop_table('response_recommendations')
    op.drop_index(op.f('ix_incident_action_plans_simulation_run_id'), table_name='incident_action_plans')
    op.drop_table('incident_action_plans')
    op.drop_index(op.f('ix_audit_events_simulation_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_scenario_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_simulation_runs_status'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_scenario_version_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_scenario_versions_scenario_id'), table_name='scenario_versions')
    op.drop_table('scenario_versions')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_disaster_type'), table_name='scenarios')
    # Dropped implicitly by op.drop_table('scenarios') below — GeoAlchemy2's
    # spatial index has no separate lifecycle to manage on the way down.
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_infrastructure_assets_criticality'), table_name='infrastructure_assets')
    op.drop_index(op.f('ix_infrastructure_assets_asset_type'), table_name='infrastructure_assets')
    # Dropped implicitly by op.drop_table('infrastructure_assets') below.
    op.drop_table('infrastructure_assets')
    # ### end Alembic commands ###

    # Postgres ENUM types are independent objects — drop_table doesn't drop
    # them, so they're removed explicitly here (otherwise a re-upgrade fails
    # with "type already exists").
    for enum_name in (
        "asset_type",
        "asset_criticality",
        "disaster_type",
        "scenario_status",
        "simulation_status",
        "event_type",
        "recommendation_priority",
        "recommendation_source",
        "recommendation_status",
        "risk_category",
        "risk_level",
        "artifact_type",
        "vulnerability_level",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
