// Re-exported from the cross-domain shared contracts (architecture.md §22) —
// this feature never redefines these shapes locally.
export type {
  AIAnalyzeRequest,
  AIDataLimitation,
  AIPriorityLevel,
  AIRecommendedAction,
  AIRequestOut,
  AIRequestResultOut,
  AIRequestStatus,
  AIRequestStatusOut,
  CommandBrief,
  DisasterType,
  HazardPhase,
  Page,
  PropagationConfig,
  PropagationHazardState,
  Scenario,
  ScenarioCreateRequest,
  ScenarioDetail,
  ScenarioListItem,
  ScenarioStatus,
  ScenarioUpdateRequest,
  SimulationRun,
  SimulationRunCreateRequest,
  SimulationRunDetail,
  SimulationState,
  SimulationStatus,
  StructureConfig,
  StructureImpact,
  StructureStatus,
  StructureType,
  TimelineFrame,
  TimelineResponse,
} from "@shared/types";
